name: Integration Tests #Any name you want for your workflow
on: #Indicates when will the workflow be triggered
  pull_request: # In this case we want it to be triggered when doing a Pull request
    branches: [main] # This event will only run when the PR is directed to the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# The workflow can have one or more jobs
jobs:
  # In this example we wil only need one job called "test"
  test:
    # This is the runner we want
    runs-on: ubuntu-latest
    # Steps are the tasks on our job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJS v16.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0
      - name: Install Dependencies
        run: npm install
      - name: Run Specs
        env:
          #BASE_URL: ${{secrets.BASE_URL}} # We take the URL from our declared secrets
          BASE_URL: "https://petstore.swagger.io/v2"
        run: npm run test

      - name: Upload Jest HTML Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: integration-report
          path: |
            reports/*
